### ISSUE TITLE
`merge_cubes` error if dim labels can't be sorted

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#102]
In the merge_cubes implementation we currently use `xarray.combine_by_coords`, which fails if a band label is a string a can't be sorted by Pandas.

```python
ValueError: Coordinate variable bands is neither monotonically increasing nor monotonically decreasing on all datasets
```

there seems to be several discussions going on about this functionality as you can see on github issues, I'm not sure what we are facing here is something new to report them or not.

https://github.com/pydata/xarray/issues?q=is%3Aissue+combine_by_coords

I attach a notebook showing when the error happens and possible workarounds, as discussed couple of days ago:
[test_add_dimension.zip](https://github.com/Open-EO/openeo-processes-dask/files/11404756/test_add_dimension.zip)

@LukeWeidenwalker @ValentinaHutter

**Comment by clausmichele** [comment]
@LukeWeidenwalker when do you plan to address this? I would need this and the comparison processes as soon as possible.

**Comment by LukeWeidenwalker** [comment]
Valentina has updated the comparison PR to adhere to the new nodata policy, I've yet to review these changes, but I'll do this asap. For merge_cubes, I'll try to make time this week.
