### ISSUE TITLE
`merge_cubes` fails if some attrs are different

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#114]
I'm doing some tests with the client side processing and I found this bug. I am using two netCDFs with a common property, but different values (due to a recent update of the VITO back-end):

```
institution :
    openEO platform - Geotrellis backend: 0.9.5a1

institution :
    openEO platform - Geotrellis backend: 0.11.0a1
```

The error is:
`MergeError: combine_attrs='no_conflicts', but some values are not the same.`

The solution is easy, we just have to set the combine_attrs="drop_conflicts" (default is "no_conflicts") in the following lines:

https://github.com/Open-EO/openeo-processes-dask/blob/b037b0a3e7981c974926c4ac8fc8c552ea6fe04f/openeo_processes_dask/process_implementations/cubes/merge.py#L112

https://github.com/Open-EO/openeo-processes-dask/blob/b037b0a3e7981c974926c4ac8fc8c552ea6fe04f/openeo_processes_dask/process_implementations/cubes/merge.py#L193

@LukeWeidenwalker could you include this in the next release along with the other `merge_cubes` fixes?

**Comment by LukeWeidenwalker** [comment]
Ah, thanks for raising this, will do!
