### ISSUE TITLE
Meaning of reduced_dimensions_min_values

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#12]
I was wondering why the attribute `reduced_dimensions_min_values` is being added when a `reduce_dimension` process is executed
https://github.com/Open-EO/openeo-processes-dask/blob/166d49d0f933af69554dadb0cc1b5b87b4782349/openeo_processes_dask/process_implementations/cubes/reduce.py#L26

it is causing me some problems when trying to save the xArray.DataArray to a netCDF using the .to_netcdf() notation:

```TypeError: Invalid value for attr 'reduced_dimensions_min_values': {'t': numpy.datetime64('2017-06-03T00:00:00.000000000'), 'bands': 'VH'}. For serialization to netCDF files, its value must be of one of the following types: str, Number, ndarray, number, list, tuple```

**Comment by clausmichele** [comment]
I agree that having a metadata entry with some information about the original data could be useful, especially for reproducibility. However, maybe this information could be an entry of the STAC item generated with the result instead of embedding it into the netCDF?
@m-mohr sorry for tagging you again, but do you know if there is a STAC field that could fit this scenario?

**Comment by m-mohr** [comment]
I can't follow what you are trying to achieve, but maybe something in the processing or datacube extension?
https://github.com/stac-extensions/processing
https://github.com/stac-extensions/datacube

**Comment by clausmichele** [comment]
@jdries did you ever consider in adding some metadata about the temporal extent of the input data used to produce the result of a reduce_dimension('temporal') ?

**Comment by clausmichele** [comment]
@SerRichard I see. For me it's also fine to keep it, even if it seems quite EODC specific, but we would need to document it! Anyway, how do you handle it in save_result when writing a netCDF? Because that is where my question came from, since I get an error if I leave it in the attrs.

**Comment by clausmichele** [comment]
By the way, this forum issue is also somehow related https://discuss.eodc.eu/t/add-a-time-acquisition/256

**Comment by clausmichele** [comment]
> Adding to the discussion in #18, could this be another place where an `.openeo` xarray accessor could be useful? Afaik these fields shouldn't be considered when serialising, and it could be a good place to store these rather arbitrary metadata items? Let me know what you think!

continuing the discussion, @LukeWeidenwalker how do we proceed here? Can we move this `reduced_dimensions_min_values` attribute to the new `.openeo` accessor so that it doesn't interfere with netCDF serialization?

**Comment by LukeWeidenwalker** [comment]
> > Adding to the discussion in #18, could this be another place where an `.openeo` xarray accessor could be useful? Afaik these fields shouldn't be considered when serialising, and it could be a good place to store these rather arbitrary metadata items? Let me know what you think!
> 
> continuing the discussion, @LukeWeidenwalker how do we proceed here? Can we move this `reduced_dimensions_min_values` attribute to the new `.openeo` accessor so that it doesn't interfere with netCDF serialization?

Yes, I think what you propose is the right next step! 
So, basically the idea is to preserve a summary of any dimension that is reduced, so that if appropriate you can add the dimension back in with a size of 1 and label the row with this. How do we feel about naming this `data.openeo.reduced_dimension_summary`? I don't have bandwidth to do this right now, but always happy to review a PR to address this!
