### ISSUE TITLE
Enable Python 3.11

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#133]
@LukeWeidenwalker could you please try to enable Python 3.11 as well? This would allow to align with https://github.com/Open-EO/openeo-pg-parser-networkx which already supports it.

**Comment by LukeWeidenwalker** [comment]
I don't have bandwidth to work on this right now, but ofc happy to review any incoming PRs! 

Linking to my recommendations for how to do this in https://github.com/Open-EO/openeo-python-client/pull/434#discussion_r1238613033?

**Comment by clausmichele** [comment]
Ok, I thought I would need some more specific permissions on the repo to run the tests. I'll do it!

**Comment by clausmichele** [comment]
https://github.com/Open-EO/openeo-processes-dask/pull/134
