### ISSUE TITLE
openEO exceptions 

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#15]
Looking at the current implementation of the openEO expections I was thinking about possible improvements. Currently, a new class is defined for every exception.
I tested successfully a dynamic way of generating an exception class, could we discuss about it @LukeWeidenwalker?
I could create a PR soon!

It would avoid to create a new class for every new exception, we would just have to add it to the dictionary.
It would also avoid to have to import all the exceptions like:
`from openeo_processes_dask.exceptions import ProcessParameterMissing`
Additionally, it can also return a class with a custom message if it's not already in the dict.

```python
from typing import Optional

openeo_exceptions_dict_mapping = {
    "DimensionNotAvailable": "A dimension with the specified name does not exist.",
    "DimensionLabelCountMismatch": "The number of dimension labels exceeds one, which requires a reducer.",
    "ArrayElementParameterConflict" : "The process `array_element` only allows that either the `index` or the `labels` parameter is set.",
    "ArrayElementParameterMissing" : "The array has no element with the specified index or label.",
    "ArrayNotLabeled" : "The array is not a labeled array, but the `label` parameter is set. Use the `index` instead.",
    "ArrayElementNotAvailable" : "The array has no element with the specified index or label.",
    "TooManyDimensions": "The number of dimensions must be reduced to three for `aggregate_spatial`."
}

def exception_constructor(self, msg):
    self.message = msg
    
def exception_to_string(self):
    return self.message

def OpenEOException(openeo_exception: str = None,
                      message: Optional[str] = None):
    exception_class = type(openeo_exception, (Exception, ), {
    "__init__": exception_constructor,
    "__str__": exception_to_string
    })
    if message is not None:
        return exception_class(openeo_exception,message)
    else:
        return exception_class(openeo_exceptions_dict_mapping[openeo_exception])
```

The usage would be
```python

from openeo_processes_dask.exceptions import OpenEOException

raise OpenEOException("DimensionNotAvailable")
```

**Comment by LukeWeidenwalker** [comment]
Thanks for the suggestion - I just tried this, and it seems that this change would prevent catching these exceptions with except.

```
try:
    raise OpenEOException("DimensionNotAvailable")
except OpenEOException:  # same with `except OpenEOException("DimensionNotAvailable"):`
    print("caught")
```
gives a TypeError.

Why do you think this change is necessary?

**Comment by clausmichele** [comment]
I opened this issue to discuss about possible alternatives, I don't think it is strictly necessary to change the current implementation. I was trying to see if there is a way to simplify the creation of new custom exceptions with as less lines of code as possible.

This would allow to catch the custom exceptions, either with a general openeo one or the specific one depending on how it is implemented:

```python
openeo_exceptions_dict_mapping = {
    "DimensionNotAvailable": "A dimension with the specified name does not exist.",
    "DimensionLabelCountMismatch": "The number of dimension labels exceeds one, which requires a reducer.",
    "ArrayElementParameterConflict" : "The process `array_element` only allows that either the `index` or the `labels` parameter is set.",
    "ArrayElementParameterMissing" : "The array has no element with the specified index or label.",
    "ArrayNotLabeled" : "The array is not a labeled array, but the `label` parameter is set. Use the `index` instead.",
    "ArrayElementNotAvailable" : "The array has no element with the specified index or label.",
    "TooManyDimensions": "The number of dimensions must be reduced to three for `aggregate_spatial`."
}

class openEOException(Exception):
    pass

def openeo_exception_1(name, message=None):
    if message is None:
        message = openeo_exceptions_dict_mapping[name]
    """Dynamically create custom Error class."""
    return type(name, (openEOException,), {})(message)

try:
    raise openeo_exception_1("DimensionNotAvailable")
except openEOException:
    print("caught 1")
    
def openeo_exception_2(name):
    """Dynamically create custom Error class."""
    return type(name, (openEOException,), {})


try:
    error = openeo_exception_2("DimensionNotAvailable")
    raise error(openeo_exceptions_dict_mapping["DimensionNotAvailable"])
except openEOException:
    print("caught 2")

```

**Comment by LukeWeidenwalker** [comment]
Thanks for the updated example! Hmmmmm. Not sure what I think about this. I think personally I'd prefer just importing these exceptions when needed, the extra lines of code of having the classes defined in exceptions.py don't really bother me. 

We could totally have a base `OpenEOException` class though, I think that would make sense for all these. Also I don't like that `TooManyDimensions`, `DimensionNotAvailable` and `DimensionLabelCountMismatch` have a message predefined, I'm going to remove these and add the message within the process. 

Yeah, I think I'd be inclined to close this for now, but keep the examples you provided in mind for how to create them dynamically when it becomes clearer that this is necessary!
