### ISSUE TITLE
`linear_scale_range` does not clip input data

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#150]
The current implementation of `linear_scale_range` is not conform to the specification: https://processes.openeo.org/#linear_scale_range
since it does not clip the data before doing the scaling operation.

> The given number in x is clipped to the bounds specified in inputMin and inputMax

**Comment by clausmichele** [comment]
PR for fix is here: https://github.com/Open-EO/openeo-processes-dask/pull/151

**Comment by LukeWeidenwalker** [comment]
Merged - thanks!
