### ISSUE TITLE
Dimension renamings

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-dask#18]
I'm facing the following design decision and wanted to get some input! @ValentinaHutter @SerRichard 

So, currently we have this `@normalise_output_datacube` function, which renames the dimensions in the datacube such that the other processes can just use `data["x"]`, `data["time"]`, etc. instead of having to resolve dimension names everywhere. 

Because the dimensions are renamed, any references to those dimensions that are passed as parameters (e.g. `def reduce_dimension(data, dimension=...)` obviously need to be renamed as well. This behaviour I've previously shoe-boxed into the `@process` decorator, where the `dimension` parameter gets renamed too according to the mapping in `RENAME_DIMS`. 

However, I'm now quite convinced that both `ProcessRegistry` and `@process` should live in openeo-pg-parser-networkx (they resolve parameters within a process graph, which openeo-processes-dask has no business in). However, I don't think `RENAME_DIMS` should join this migration, because this is a direct manipulation on the datacube abstraction, this logic really wants to stay here.

So, where to do what `RENAME_DIMS` has been doing so far?

I think we have the following options:
1) Keep renaming dims in `@normalise_output_datacube` and add a second `@normalise_parameters` decorator
	- This would need to be added to all the processes that manipulate dimensions. 
	- The resulting datacube will not have the same dimensions as was input by the user (unless we add some hack to rename back at the end)
2) Don't touch the dimension names and rather resolve to the right dimension name within the processes
        - This could be achieved by adding an xarray accessor (e.g. `dataarray.openeo`), see [docs](https://docs.xarray.dev/en/stable/internals/extending-xarray.html)
        - This would be similar in spirit to what was done previously with `get_time_dimension_from_data`, but for all dimensions and in a consistent interface
        - I.e. instead of doing `data["x"]`, we'd do `data[data.openeo.x]`. In this accessor, we could then do that mapping from `longitude` or other aliases to whatever the dimension is actually called.
	- This has the added benefit of not altering the dimensions the user provides
	- This is also something we'd have to start using throughout the codebase
	- I'd have to check whether this accessor actually survives most transformations, if not we'll have to add a test to make sure processes don't drop this.

I think currently I'd be in favour of adopting option 2) as a convention - curious what you think! Any further options I'm not seeing here?

This might seem inconsequential, but I actually think it's kind of important, because it goes towards defining what an openeo datacube really means in our implementation.

**Comment by clausmichele** [comment]
My 2 cents: keep in mind that there are not only spatial, temporal and band dimensions. Ideally an openEO datacube could have N dimensions and the processes should be able to handle them. Anyway, I also agree that the parser code should not manipulate dimension names.

**Comment by SerRichard** [comment]
>        * I'd have to check whether this accessor actually survives most transformations, if not we'll have to add a test to make sure processes don't drop this.

This could be the trickiest sticking point, if some xarray (or other) process may manipulate the dimension names and values, then there could be an issue. I am not sure how many (if any) examples of this currently exist in the codebase.

I'm a bit agnostic on the two options currently. @clausmichele Raises a point in the case where dim is a process parameter. @LukeWeidenwalker Are you talking about cases of `data["x"]` and also `data[dim]`, if it's only the former then it should avoid stepping on the toes of any dim defined by the user?

**Comment by LukeWeidenwalker** [comment]
> My 2 cents: keep in mind that there are not only spatial, temporal and band dimensions. Ideally an openEO datacube could have N dimensions and the processes should be able to handle them. 
Good point! Tbh, it seems like that would be easier to achieve when we don't alter dimension names and instead add an accessor to retrieve e.g. the spatial dimensions or the temporal dimension

> This could be the trickiest sticking point, if some xarray (or other) process may manipulate the dimension names and values, then there could be an issue. I am not sure how many (if any) examples of this currently exist in the codebase.

I know for example that `resample_spatial` renames x and y to latitude and longitude (although this is handled in place)!

> Are you talking about cases of data["x"] and also data[dim], if it's only the former then it should avoid stepping on the toes of any dim defined by the user?
I think mostly about `data["x"]` or `data["time"]` as in `resample_temporal`, or `aggregate_spatial`. For `data[dim]` there isn't really a problem, right? If we don't change anything in the dimension name, then that should already access the right dimension.

**Comment by LukeWeidenwalker** [comment]
I've cobbled together a [draft PR](https://github.com/Open-EO/openeo-processes-dask/pull/20) with the `.openeo` accessor approach, would be great to get some feedback! :)

**Comment by LukeWeidenwalker** [comment]
Closed with #20, thanks for the input!
