### ISSUE TITLE
Inconsistent behavior of reducers "max", "median" and "mean" with respect to "nan"

### ISSUE THREAD

**Issue by julianmeyerarnek** [Open-EO/openeo-processes-dask#181]
At current, the behavior of 
 - `reduce_dimension('x', reducer='median')` and 
 - `reduce_dimension('x', reducer='mean')` is different with respect to `nan`-values.
  	
For "median": `ignore_data` is set to `True` per default (https://github.com/Open-EO/openeo-processes-dask/blob/7ddf6c2aae7d8befa22d3746eacef16c83ba31b0/openeo_processes_dask/process_implementations/math.py#L122), 
whereas `ignore_data` for `mean` is set to `False` per default (https://github.com/Open-EO/openeo-processes-dask/blob/7ddf6c2aae7d8befa22d3746eacef16c83ba31b0/openeo_processes_dask/process_implementations/math.py#L129)

I suggest to have a consistent handling of `nan` for all reducers and would prefer the behavior of `median`.

And: I seems to me that I cannot "overrule" the pre-defined behavior - not even by providing kw-args.

An example Jupyter Notebook comparing `mean` and `median`-reducers can be found here: 
https://github.com/julianmeyerarnek/S5P_L3_O3_openEO

**Comment by m-mohr** [comment]
The default specified in the openEO processes is ignore_nodata=True, so all processes should default to True (i.e. the behavior of median)

**Comment by clausmichele** [comment]
Thanks @julianmeyerarnek to report this.
Before that the fix gets merged https://github.com/Open-EO/openeo-processes-dask/pull/183, you can use this workaround to set `ignore_nodata=True` explicitly:

```python
from openeo.processes import mean
def mean_reducer(data):
    return mean(data,ignore_nodata=True)
task_reduce_lon_mean = task_reduce_time_mean.reduce_dimension('x', reducer=mean_reducer)
```

which would produce the correct result:
![Untitled](https://github.com/Open-EO/openeo-processes-dask/assets/31700619/56821c3a-da15-4315-9e26-a2931a101980)

@ValentinaHutter @GeraldIr it would be necessary to check why the tests didn't show this behaviour and add a specific one if it's missing

.
