### ISSUE TITLE
filter_bbox: No crs => error

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes-dask#214]
If I provide a bbox to filter_bbox without a CRS:
```json
{
          "west": 16.1,
          "south": 48.1,
          "east": 16.6,
          "north": 48.6
}
```

I get an error:
> Unexpected exception: 'dict' object has no attribute 'crs'

I guess parsing some datatypes in openeo-pg-parser-networkx is not ideal...

**Comment by m-mohr** [comment]
I'm doing individual process tests for the test suite, so there's no full process graph. I'm directly accessing the filter_bbox process with the extent above and a xarray DataArray.

**Comment by GeraldIr** [comment]
So you're passing a dict directly to a function that is expecting a BoundingBox object?

**Comment by m-mohr** [comment]
Yes, I'm not using openeo-pg-parser-networkx. Am I expected to still import it although I'm not using it to use the BoundingBox class? I'm also not quite sure how I have to use the BoundingBox class.

**Comment by GeraldIr** [comment]
I don't see why it would be converted automatically.

Also the parser is a direct dependency for the openeo-processes-dask library and BoundingBox gets imported regardless.

If you want to call the function directly you'll have to make a BoundingBox object like so:

```
from openeo_pg_parser_networkx.pg_schema import BoundingBox

bb = BoundingBox(**extent)
```

and then pass bb into the function.

**Comment by m-mohr** [comment]
Yeah, I guess the dependency on the parser is what bugs me.

Thanks for the example, doing that solves the issue for the test suite at least.
