### ISSUE TITLE
joblib missing from requirements

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#216]
The recent merge of aggregate_spatial introduced the requirement of joblib, which is not installed since it's missing from the pyproject.toml.
Please add it as soon as possible, otherwise the code can't be used directly but joblib must be installed manually.

@masawdah @GeraldIr @ValentinaHutter

**Comment by masawdah** [comment]
I fixed that with this new pull request  https://github.com/Open-EO/openeo-processes-dask/pull/217  and used the new XVEC functionality for spatial aggregation.
