### ISSUE TITLE
hardcoded spatial dims labels in `resample_spatial`

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#228]
Instead of `"x"` and `"y"` we should use `data.openeo.x_dim` and `data.openeo.y_dim`.
I will fix it in a PR.

https://github.com/Open-EO/openeo-processes-dask/blob/main/openeo_processes_dask/process_implementations/cubes/resample.py#L78-L82

**Comment by ValentinaHutter** [comment]
merged - thank you!
