### ISSUE TITLE
fix aggregate spatial tests

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-processes-dask#252]
Currently, aggregate spatial tests, that had worked before, are failing, which needs further investigation. For now, we will disable these tests, in order to unblock us from development work.

**Comment by clausmichele** [comment]
@ValentinaHutter I run the `aggregate_spatial` tests and on my side the run fine, the issue arise due to the latest xarray version! Fixing it in pyproject.toml solves the issue, I've done it in this PR: https://github.com/Open-EO/openeo-processes-dask/pull/259
