### ISSUE TITLE
HTTP wrapper missing?

### ISSUE THREAD

**Issue by romeokienzler** [Open-EO/openeo-processes-dask#61]
After quite some digging I was not able to find instructions on how to get started with the https://github.com/Open-EO/openeo-processes-dask backend (other than installing the dependencies and running the tests, which works fine for me) - do you have any hint?

After some chats with @m-mohr and Jonas Eberle they've [recommended](https://matrix.to/#/!OVMmWSUpHZUBAzrxjp:gitter.im/$0oGwszhgpe0M6Meq90nYNduSfOurEWDCOSfi_oucC7Y?via=gitter.im) to open an issue on your side. 

I'm interested in getting my hands dirty with [openeo-processes-dask](https://github.com/Open-EO/openeo-processes-dask) - basically connecting the python OpenEO client to it

**Comment by LukeWeidenwalker** [comment]
Hi Romeo - I think you're looking for the [openeo-pg-parser-networkx](https://github.com/Open-EO/openeo-pg-parser-networkx) repository. This contains the code to parse and execute a process graph, and contains instructions for how to register process implementations from an arbitrary source (e.g. openeo-processes-dask) to the registry of available processes.

I should have really linked to there in the readme, it really isn't obvious that the parser is what one needs to execute a process graph - I'll do that asap!

If you run into any problems, please don't hesitate to open further issues, more than happy to help! :)

**Comment by m-mohr** [comment]
What he's looking for is the "the full thing", so basically the docker image with API "wrapper", pg parser, processes-dask etc combined or at least a hint how to do that. Because the Python client can't directly connect to the pg parser, of course. Maybe that's something you or @clausmichele could help with?

**Comment by clausmichele** [comment]
I'm actually working on that, currently based on our processes implementation and later will move to openeo-processes-dask and openeo-pg-parser-networkx.

**Comment by romeokienzler** [comment]
Thanks @clausmichele - yes, saw it in the last monthly meeting, thanks so much for pointing this out
