### ISSUE TITLE
Add list of implemented processes and their status

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#67]
How could we keep track of the currently implemented openEO processes of this project? It would be nice to know:
- What is implemented and fully working
- What is implemented but still lacking some functionalities
- What is under development
- What is planned to be implemented soon

In this way it would be much easier to contribute.

**Comment by clausmichele** [comment]
Thanks for the complete reply Lukas. I also agree that having a simple list is not ideal but I wanted to discuss about different possibilities and approaches.

It's also fine for me to handle through GitHub issues the problems related to specific processes.

Anyway, I am quite open to possible contributions. Recently I noticed that the `filter_spatial`, `filter_bbox` and `filter_temporal` processes are missing and I wanted to know if I could go on with a PR or wait, if there's already something in progress.
So, it would be really nice if you could add to GitHub your internal JIRA issues, which would allow me to decide what do do!

**Comment by LukeWeidenwalker** [comment]
Added the missing issues and assigned those that we're currently working on - #75 is the one for filtering, happy to review when you have something! :)

**Comment by ValentinaHutter** [comment]
A number of processes were added recently (SAP10), so I now updated the list of missing processes by creating new issues: 
- https://github.com/Open-EO/openeo-processes-dask/issues/304
- https://github.com/Open-EO/openeo-processes-dask/issues/303
- https://github.com/Open-EO/openeo-processes-dask/issues/305
