### ISSUE TITLE
Add support for labelled arrays

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-dask#73]
- [x] array_labels
- [x] array_find_label (optional in core profile)
- [x] array_create_labeled (optional in core profile)

We'll need to figure out how we can support labelled arrays. It's easy for datacubes, there the labels are just the xr.Dataarray coordinates. But how do we get these down into child processes? E.g. an apply_dimension wrapping `array_labels`, all that's currently ending up in `array_labels` is the raw numpy array without the labels.

**Comment by clausmichele** [comment]
`NotImplementedError: labelled arrays are currently not implemented. Please use index instead.`

I encountered this error trying to compute the NDVI passing the bands labels to the `array_element` process.

Is there some development going on to solve this issue?

**Comment by LukeWeidenwalker** [comment]
No, we're not currently working on this!

**Comment by clausmichele** [comment]
Implementation is in this PR https://github.com/Open-EO/openeo-processes-dask/pull/155
