### ISSUE TITLE
Core profile: Complete filter processes

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-dask#75]
- [x] filter_bbox (https://github.com/Open-EO/openeo-processes-dask/pull/118)
- [x] filter_temporal (#76)
- [ ] filter_spatial
- [x] filter_bands(#105)

**Comment by clausmichele** [comment]
Just noticed that `filter_bands` is also missing.

**Comment by clausmichele** [comment]
filter_bands here https://github.com/Open-EO/openeo-processes-dask/pull/105

**Comment by m-mohr** [comment]
fyi: The core profile will be updated in a couple of weeks.

**Comment by clausmichele** [comment]
`filter_spatial` has been implemented and merged with this PR: https://github.com/Open-EO/openeo-processes-dask/pull/170
