### ISSUE TITLE
Core profile: Complete aggregate processes

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#77]
* [x] aggregate_spatial (https://github.com/Open-EO/openeo-processes-dask/issues/26): implemented with https://github.com/Open-EO/openeo-processes-dask/pull/217
 * [x] aggregate_temporal_period (https://github.com/Open-EO/openeo-processes-dask/issues/27)
 * [x] aggregate_temporal

**Comment by m-mohr** [comment]
aggregate_temporal has a stub and is reported as implemented, but then it rerusn an error. It should be removed until it's fully implemented.

> raise NotImplementedError("aggregate_temporal is currently not implemented")
