### ISSUE TITLE
Implement `filter_bands`

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-processes-dask#99]
This issue is to implement the `filter_bands` process and add support for arbitrary dimension names with dimension types.

From https://github.com/Open-EO/openeo-processes-dask/pull/96#discussion_r1183569626:

> `type` is currently ignored. Ideally this would be worked into the `.openeo` accessor in `_xr_interop.py`, as an extra list for each type of dimension (e.g. "known_spatial_dims", etc.) that the name of this dimension is appended to and considered when `.openeo.spatial_dims` is called.

**Comment by clausmichele** [comment]
From the process definition, we should also be able to filter giving the wavelengths https://processes.openeo.org/#filter_bands @LukeWeidenwalker I suspect that the wavelength attribute is not included in the xarray dataarray object metadata right?
I would like to implement it without wavelengths at the moment, and raise an error if someone tries to use it. I think I never seen an example using it yet.

**Comment by LukeWeidenwalker** [comment]
No, it's not reliably available right now. If it should be, we'd have to explicitly fetch and set it in `load_collection`. But if nobody uses this right now, there's no rush in supporting it I think.

I think we could also just exclude the `wavelengths` parameter from the spec, then users would be warned at the client level already!

**Comment by clausmichele** [comment]
Ok good idea, let's try like that.
